textadventureproject/textadventureapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='textadventureapp'
urlpatterns = [
    path('', views.station, name='station'),
    path('<str:name>', views.station, name='station'),
]

textadventureproject/textadventureproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('textadventureapp/', include('textadventureapp.urls')),
]

textadventureproject/textadventureapp/models.py
from django.db import models

# Create your models here.
class Station(models.Model):
    name = models.CharField(max_length=50, unique=True)
    title = models.CharField(max_length=200)
    bildname = models.CharField(max_length=200, default=True)
    text = models.TextField()

    def __str__(self):
        return self.name

class Choice(models.Model):
    station = models.ForeignKey(to=Station, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    next_station = models.ForeignKey(to=Station, on_delete=models.CASCADE, related_name="incoming_set")

    def __str__(self):
        return f"{self.text}: {self.next_station.name}"

textadventureproject/textadventureapp/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse

from .models import Choice, Station

# Create your views here.

def station(request, name="start"):
    station = get_object_or_404(Station, name=name) 
    return render(request, "textadventureapp/station.html", {"station": station})

textadventureproject/textadventureapp/templates/textadventureapp/station.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% load static %}
    <link href="{% static 'textadventureapp/images' %}">
    <title>Text-Adventure</title>
</head>
<body>

    <div class="container mt-5">
    <div class="card">
        <div class="card-body">
        <h5 class="card-title">{{station.title}}</h5>
        <p class="card-text">{{station.text}}</p>
        {% if station.bildname %}
            <img src="{% static station.bildname %}" alt="image">
        {% endif %}
        {% for choice in station.choice_set.all %}
            <a href="{{choice.next_station.name}}" class="">{{choice.text}}</a></br>
        {% endfor %}
        </div>
    </div>
    </div>
</body>
</html>